const teamData = [
  {
    name: "Vish Sahasranamam",
    verticals: ["Forge.Labs", "Forge.Academy", "Forge.Lighthouse", "Forge.Foundry", "Forge.Fast", "Forge.Fund"],
    category: "Executive Leadership",
    displayRole: "Co-founder & CEO",
    displayRole2: "",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "https://www.linkedin.com/in/vishforge/",
    email: "",
    about: ""
  },
  {
    name: "Meera",
    verticals: ["Forge.Lighthouse", "Forge.Academy"],
    category: "Executive Leadership",
    displayRole: "Vice President & Chief Program Officer",
    displayRole2: "",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "https://www.linkedin.com/in/lakshmimeera/",
    email: "",
    about: ""
  },
  {
    name: "Arun Suresh",
    verticals: ["Forge.Foundry", "Forge.Lighthouse", "Forge.Fast"],
    category: "Executive - General Management",
    displayRole: "Head - Forge4Fauj",
    displayRole2: "Principal",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "https://www.linkedin.com/in/arun-suresh-profile/",
    email: "",
    about: ""
  },
  {
    name: "Thanushree",
    verticals: ["Forge.Fund", "Forge.Fast", "Forge.Foundry"],
    category: "Executive - General Management",
    displayRole: "Head - Forge.Fund",
    displayRole2: "Principal",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "https://www.linkedin.com/in/thanushree-anand-2a87b69b/",
    email: "",
    about: ""
  },
  {
    name: "Sarathi S",
    verticals: ["Forge.Foundry"],
    category: "Executive - Program Management",
    displayRole: "Program Manager - Forge4Fauj",
    displayRole2: "",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "https://www.linkedin.com/in/sarathi-sriraman-207059a2/",
    email: "",
    about: ""
  },
  {
    name: "Guruprasad Sharma",
    verticals: ["Forge.Fund", "Forge.Ops"],
    category: "Experts",
    displayRole: "Specialist - Forge.Fund",
    displayRole2: "Lead - MarComm",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "https://www.linkedin.com/in/guruprasad-sharma-531b3a136/",
    email: "",
    about: ""
  },
  {
    name: "Dinesh Guntur",
    verticals: ["Forge.Fund", "Forge.Foundry"],
    category: "Experts",
    displayRole: "Sr. Analyst",
    displayRole2: "",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "https://www.linkedin.com/in/dineshguntur/",
    email: "",
    about: ""
  },
  {
    name: "Sowmya GL",
    verticals: ["Forge.Fast", "Forge.Fund", "Forge.Foundry"],
    category: "Experts",
    displayRole: "Specialist - Forge.Ventures",
    displayRole2: "Program Manager - CEO’s Office",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "https://www.linkedin.com/in/sowmya-gl-ab335521/",
    email: "",
    about: ""
  },
  {
    name: "Gayathri Kennady",
    verticals: ["Forge.Ops"],
    category: "Enablers",
    displayRole: "Associate - People & Talent",
    displayRole2: "",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "https://www.linkedin.com/in/gayathri-kennady-515443149/",
    email: "",
    about: ""
  },
  {
    name: "Hema Priyadarshini R",
    verticals: ["Forge.Ops", "Forge.Academy"],
    category: "Executive - Program Management",
    displayRole: "Program Lead - Forge.Academy",
    displayRole2: "Lead - CEO's Office",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "https://www.linkedin.com/in/hema-priyadharshini-karthik-b98bb637/",
    email: "",
    about: ""
  },
  {
    name: "Jeejy Theophilus",
    verticals: ["Forge.Labs"],
    category: "Experts",
    displayRole: "Sr. Engineer - Forge.Labs",
    displayRole2: "",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "https://www.linkedin.com/in/jeejy-theophilus-j/",
    email: "",
    about: ""
  },
  {
    name: "Karthik Das",
    verticals: ["Forge.Fund", "Forge.Ops", "Forge.Lighthouse"],
    category: "Experts",
    displayRole: "Sr. Analyst - Forge.Lighthouse",
    displayRole2: "",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "https://www.linkedin.com/in/karthikdas25/",
    email: "",
    about: ""
  },
  {
    name: "Khavya",
    verticals: ["Forge.Labs"],
    category: "Experts",
    displayRole: "Engineer - Forge.Labs",
    displayRole2: "",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "https://www.linkedin.com/in/khavyapriya/",
    email: "",
    about: ""
  },
  {
    name: "Lakshmanan M",
    verticals: ["Forge.Ops"],
    category: "Enablers",
    displayRole: "Associate - MarComm",
    displayRole2: "",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "https://www.linkedin.com/in/lakshmanan3217/",
    email: "",
    about: ""
  },
  {
    name: "Mahesh V",
    verticals: ["Forge.Labs", "Forge.Academy"],
    category: "Experts",
    displayRole: "Associate VP & Director - Forge.Academy",
    displayRole2: "",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "https://www.linkedin.com/in/dr-mahesh-veezhinathan-1ba08040/",
    email: "",
    about: ""
  },
  {
    name: "Murugesan V",
    verticals: ["Forge.Labs"],
    category: "Experts",
    displayRole: "Lead - IT.Ops",
    displayRole2: "",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "https://www.linkedin.com/in/murugesan-vellinigiri-64b80558/",
    email: "",
    about: ""
  },
  {
    name: "Muthukumar K",
    verticals: ["Forge.Labs"],
    category: "Experts",
    displayRole: "Lead - Gen.Admin",
    displayRole2: "",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "https://www.linkedin.com/in/muthukumar-k-52ba22123/",
    email: "",
    about: ""
  },
  {
    name: "Nadi Kannan K",
    verticals: ["Forge.Ops"],
    category: "Enablers",
    displayRole: "Associate - Finance & Accounts",
    displayRole2: "",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "https://in.linkedin.com/in/nadi-kannan-k-1b745a21b",
    email: "",
    about: ""
  },
  {
    name: "Praveen Kumar",
    verticals: ["Forge.Academy"],
    category: "Executive - Program Management",
    displayRole: "Engineer - Forge.Labs",
    displayRole2: "",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "https://www.linkedin.com/in/praveenkumarmpk/",
    email: "",
    about: ""
  },
  {
    name: "Ramkumar SP",
    verticals: ["Forge.Academy"],
    category: "Executive Leadership",
    displayRole: "Program Lead - Forge.Academy",
    displayRole2: "",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "https://www.linkedin.com/in/ramkumar12/",
    email: "",
    about: ""
  },
  {
    name: "Rithin Shaji",
    verticals: ["Forge.Ops"],
    category: "Enablers",
    displayRole: "Associate - IT.Ops",
    displayRole2: "",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "https://www.linkedin.com/in/rithin-shaji-68283b196/",
    email: "",
    about: ""
  },
  {
    name: "Sabareesh G",
    verticals: ["Forge.Ops"],
    category: "Enablers",
    displayRole: "Engineer - Forge.Labs",
    displayRole2: "",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "https://www.linkedin.com/in/sabareesh-g-375188237/",
    email: "",
    about: ""
  },
  {
    name: "Sai Suneela",
    verticals: ["Forge.Ops"],
    category: "Enablers",
    displayRole: "Lead - Gen.Admin",
    displayRole2: "",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "https://www.linkedin.com/in/sai-suneela-v-s-2b7945256/",
    email: "",
    about: ""
  },
  {
    name: "Sarveswaran S",
    verticals: ["Forge.Labs"],
    category: "Experts",
    displayRole: "Engineer - Forge.Labs",
    displayRole2: "",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "https://www.linkedin.com/in/sarveswaran-s-187bb8128/",
    email: "",
    about: ""
  },
  {
    name: "Sathish S",
    verticals: ["Forge.Labs"],
    category: "Experts",
    displayRole: "Manager - Facilities & Infra",
    displayRole2: "",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "https://www.linkedin.com/in/sathish-s-7833b2122/",
    email: "",
    about: ""
  },
  {
    name: "Selvakumar J",
    verticals: ["Forge.Labs"],
    category: "Experts",
    displayRole: "Specialist",
    displayRole2: "",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "https://www.linkedin.com/in/selva-j-134629155/",
    email: "",
    about: ""
  },
  {
    name: "Sriram R",
    verticals: ["Forge.Ops"],
    category: "Executive Leadership",
    displayRole: "Associate VP & Director - Finance & Operations",
    displayRole2: "",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "https://www.linkedin.com/in/sriram-r-460134148/",
    email: "",
    about: ""
  },
  {
    name: "Sriram Ramachandran",
    verticals: ["Forge.Labs"],
    category: "Experts",
    displayRole: "Associate - Finance & Accounts",
    displayRole2: "",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "https://www.linkedin.com/in/sri-ram-386873222/",
    email: "",
    about: ""
  },
  {
    name: "Upasana Srinivasan",
    verticals: ["Forge.Ops"],
    category: "Executive Leadership",
    displayRole: "Head - People & Talent",
    displayRole2: "Manager - CEO's Office",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "https://www.linkedin.com/in/upasanasrinivasan/",
    email: "",
    about: ""
  },
  {
    name: "Vimal",
    verticals: ["Forge.Ops"],
    category: "Enablers",
    displayRole: "Associate - IT.Ops",
    displayRole2: "",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "https://www.linkedin.com/in/vima1-s/",
    email: "",
    about: ""
  },
  {
    name: "Jeevanandham R",
    verticals: ["Forge.Ops"],
    category: "Experts",
    displayRole: "Lead - Facility & Infra",
    displayRole2: "",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "",
    email: "",
    about: ""
  },
  {
    name: "Vishal N",
    verticals: ["Forge.Ops"],
    category: "Experts",
    displayRole: "Lead - Finance & Operations",
    displayRole2: "",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "https://www.linkedin.com/in/vishal-nandhakumar-6a275b246/",
    email: "",
    about: ""
  },
  {
    name: "Abinaya R",
    verticals: ["Forge.Ops"],
    category: "Enablers",
    displayRole: "Associate - People & Talent",
    displayRole2: "",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "https://www.linkedin.com/in/abinaya-ar/",
    email: "",
    about: ""
  },
  {
    name: "Prince Anand",
    verticals: ["Forge.Ops"],
    category: "Experts",
    displayRole: "Sr. Analyst - Forge.Foundry",
    displayRole2: "",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "https://www.linkedin.com/in/prince007/",
    email: "",
    about: ""
  },
  {
    name: "Samsundar",
    verticals: ["Forge.Ops"],
    category: "Enablers",
    displayRole: "Associate - IT.Ops",
    displayRole2: "",
    image: "assets/People/ventures/Mask Group 2.png",
    linkedin: "",
    email: "",
    about: ""
  }
];
